import './global.css';
import { ConfigProvider } from 'antd';
import fa_IR from 'antd/es/locale/fa_IR'
import { StyledComponentsRegistry } from './registry';
import '@ant-design/v5-patch-for-react-19';

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body>
        <ConfigProvider locale={fa_IR} direction="rtl">
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
